#!/usr/bin/env bash

# ls
alias ls='ls --color=tty'
alias l='ls -lA1'
alias ll='ls -l'
alias lh='ls -lh'

# git
if [[ -f "/usr/share/bash-completion/completions/git" ]]; then
    source "/usr/share/bash-completion/completions/git"
elif [[ -f "$HOME/.dotfiles/completions/git" ]]; then
    # git-bash doesn't have the above git completions file so I copied it from Linux
    source "$HOME/.dotfiles/completions/git"
fi

# Git aliases
alias g=git
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias gcl='git config --list'
alias gco='git checkout'
alias gpp='git pull --prune'
alias gnp='git --no-pager'
alias gst='git status -sb'
alias gl='git lola'

## Git diff aliases
    # https://stackoverflow.com/a/41730200
    alias gt='git difftool --diff-filter=M'
    alias gts='git difftool --diff-filter=M --staged'

    alias gta='git difftool'
    alias gtsa='git difftool --staged'
    alias gd='git diff'
    alias gds='git diff --staged'

# Git completion for aliases
if type -t __git_complete >&/dev/null ; then
    __git_complete g __git_main
    __git_complete gb _git_branch
    __git_complete gco _git_checkout
    __git_complete gt _git_difftool
    __git_complete gts _git_difftool
    __git_complete gd _git_diff
    __git_complete gds _git_diff
    __git_complete tig _git_branch
fi
